# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayTabsIntegrationSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    pod 'BIObjCHelpers'
  	pod 'IQKeyboardManager'
  	pod 'AFNetworking'
  	pod 'Mantle'
  	pod 'Reachability'
  	pod 'Lockbox'
  	pod 'SBJson'
  	pod 'PINCache'
  	pod 'MBProgressHUD'
  	pod 'ActionSheetPicker-3.0'
  	pod 'PayCardsRecognizer'


  # Pods for PayTabsIntegrationSwift

  target 'PayTabsIntegrationSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayTabsIntegrationSwiftUITests' do
    # Pods for testing
  end

end
